<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Location;
use App\Models\Attraction;

class AttractionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Lấy location Đà Nẵng đã được seed từ bảng cũ
        $daNang = Location::where('name', 'Đà Nẵng')->first();

        if (!$daNang) {
            return; // Tránh lỗi nếu DatabaseSeeder chưa tạo được Đà Nẵng
        }

        $attractions =[
            // ================= HÀ NỘI (destination_id = 2) =================

            // 3 Attractions
            [
                'destination_id' => 2,
                'item_type'      => 'attraction',
                'name'           => 'Lăng Chủ tịch Hồ Chí Minh',
                'description'    => 'Khu di tích lịch sử và văn hóa quan trọng, nơi an nghỉ của Bác Hồ',
                'price_min'      => 0,
                'price_max'      => 0,
                'duration_hours' => 2.0,
                'open_time'      => '07:30',
                'close_time'     => '10:30',
                'rating'         => 4.8,
                'tags'           => ['lịch sử', 'văn hóa', 'gia đình'],
                'suitable_for'   => ['family', 'solo', 'couple'],
            ],
            [
                'destination_id' => 2,
                'item_type'      => 'attraction',
                'name'           => 'Văn Miếu - Quốc Tử Giám',
                'description'    => 'Trường đại học đầu tiên của Việt Nam với kiến trúc cổ kính',
                'price_min'      => 70000,
                'price_max'      => 70000,
                'duration_hours' => 2.0,
                'open_time'      => '08:00',
                'close_time'     => '17:00',
                'rating'         => 4.7,
                'tags'           => ['lịch sử', 'kiến trúc', 'chụp ảnh'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 2,
                'item_type'      => 'attraction',
                'name'           => 'Hồ Hoàn Kiếm & Đền Ngọc Sơn',
                'description'    => 'Biểu tượng của thủ đô Hà Nội, không gian đi bộ thư giãn',
                'price_min'      => 30000,
                'price_max'      => 30000,
                'duration_hours' => 1.5,
                'open_time'      => '07:00',
                'close_time'     => '18:00',
                'rating'         => 4.9,
                'tags'           => ['ngoài trời', 'tản bộ', 'ngắm cảnh'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // 3 Restaurants
            [
                'destination_id' => 2,
                'item_type'      => 'restaurant',
                'name'           => 'Phở Gia Truyền Bát Đàn',
                'description'    => 'Quán phở bò truyền thống nổi tiếng đậm vị Hà Nội xưa',
                'price_min'      => 50000,
                'price_max'      => 70000,
                'duration_hours' => 1.0,
                'open_time'      => '06:00',
                'close_time'     => '20:30',
                'rating'         => 4.6,
                'tags'           => ['ẩm thực đường phố', 'đặc sản', 'ăn sáng'],
                'suitable_for'   => ['family', 'solo', 'couple'],
            ],
            [
                'destination_id' => 2,
                'item_type'      => 'restaurant',
                'name'           => 'Bún chả Hương Liên (Bún chả Obama)',
                'description'    => 'Thưởng thức bún chả truyền thống nổi danh quốc tế',
                'price_min'      => 60000,
                'price_max'      => 100000,
                'duration_hours' => 1.0,
                'open_time'      => '08:00',
                'close_time'     => '20:30',
                'rating'         => 4.4,
                'tags'           => ['đặc sản', 'ăn trưa', 'nổi tiếng'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 2,
                'item_type'      => 'restaurant',
                'name'           => 'Chả cá Lã Vọng',
                'description'    => 'Đặc sản chả cá lăng nướng chảo ăn kèm bún và mắm tôm',
                'price_min'      => 150000,
                'price_max'      => 200000,
                'duration_hours' => 1.5,
                'open_time'      => '10:00',
                'close_time'     => '22:00',
                'rating'         => 4.3,
                'tags'           => ['đặc sản', 'nhà hàng', 'ăn tối'],
                'suitable_for'   => ['family', 'couple'],
            ],

            // 2 Hotels
            [
                'destination_id' => 2,
                'item_type'      => 'hotel',
                'name'           => 'Hanoi Old Quarter Budget Hotel',
                'description'    => 'Khách sạn nhỏ gọn, giá rẻ nằm ngay trung tâm phố cổ',
                'price_min'      => 450000,
                'price_max'      => 600000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.1,
                'tags'           => ['tiết kiệm', 'trung tâm', 'tiện lợi'],
                'suitable_for'   => ['solo', 'couple'],
            ],
            [
                'destination_id' => 2,
                'item_type'      => 'hotel',
                'name'           => 'Tirant Hotel Hanoi',
                'description'    => 'Khách sạn 4 sao phong cách cổ điển, có hồ bơi tầng thượng',
                'price_min'      => 1400000,
                'price_max'      => 1800000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.7,
                'tags'           => ['sang trọng', 'hồ bơi', 'nghỉ dưỡng'],
                'suitable_for'   => ['family', 'couple'],
            ],

            // 1 Activity
            [
                'destination_id' => 2,
                'item_type'      => 'activity',
                'name'           => 'Xem Múa Rối Nước Thăng Long',
                'description'    => 'Trải nghiệm nghệ thuật truyền thống độc đáo của văn hóa lúa nước',
                'price_min'      => 100000,
                'price_max'      => 200000,
                'duration_hours' => 1.0,
                'open_time'      => '15:00',
                'close_time'     => '21:00',
                'rating'         => 4.8,
                'tags'           => ['nghệ thuật', 'truyền thống', 'buổi tối'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // ================= TP.HCM (destination_id = 3) =================

            // 3 Attractions
            [
                'destination_id' => 3,
                'item_type'      => 'attraction',
                'name'           => 'Dinh Độc Lập',
                'description'    => 'Di tích lịch sử cấp quốc gia với kiến trúc hiện đại ấn tượng',
                'price_min'      => 65000,
                'price_max'      => 65000,
                'duration_hours' => 2.0,
                'open_time'      => '08:00',
                'close_time'     => '16:30',
                'rating'         => 4.6,
                'tags'           => ['lịch sử', 'kiến trúc', 'tham quan'],
                'suitable_for'   => ['family', 'solo', 'couple'],
            ],
            [
                'destination_id' => 3,
                'item_type'      => 'attraction',
                'name'           => 'Bảo tàng Chứng tích Chiến tranh',
                'description'    => 'Nơi lưu giữ những tài liệu và hiện vật lịch sử chân thực nhất',
                'price_min'      => 40000,
                'price_max'      => 40000,
                'duration_hours' => 2.0,
                'open_time'      => '07:30',
                'close_time'     => '17:30',
                'rating'         => 4.8,
                'tags'           => ['lịch sử', 'bảo tàng', 'văn hóa'],
                'suitable_for'   => ['solo', 'couple'],
            ],
            [
                'destination_id' => 3,
                'item_type'      => 'attraction',
                'name'           => 'Chợ Bến Thành',
                'description'    => 'Khu chợ truyền thống lâu đời, biểu tượng mua sắm của Sài Gòn',
                'price_min'      => 0,
                'price_max'      => 0,
                'duration_hours' => 1.5,
                'open_time'      => '06:00',
                'close_time'     => '18:00',
                'rating'         => 4.3,
                'tags'           => ['mua sắm', 'địa danh', 'văn hóa'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // 3 Restaurants
            [
                'destination_id' => 3,
                'item_type'      => 'restaurant',
                'name'           => 'Bánh Mì Huỳnh Hoa',
                'description'    => 'Tiệm bánh mì thịt chả nổi tiếng nhất nhì Sài Gòn, luôn xếp hàng đông',
                'price_min'      => 65000,
                'price_max'      => 75000,
                'duration_hours' => 0.5,
                'open_time'      => '13:00',
                'close_time'     => '23:00',
                'rating'         => 4.5,
                'tags'           => ['ẩm thực đường phố', 'đặc sản', 'ăn nhanh'],
                'suitable_for'   => ['solo', 'couple', 'family'],
            ],
            [
                'destination_id' => 3,
                'item_type'      => 'restaurant',
                'name'           => 'Phở Lệ',
                'description'    => 'Quán phở đậm chất miền Nam với nước dùng đậm đà, thịt mềm',
                'price_min'      => 70000,
                'price_max'      => 90000,
                'duration_hours' => 1.0,
                'open_time'      => '06:00',
                'close_time'     => '01:00',
                'rating'         => 4.6,
                'tags'           => ['đặc sản', 'ăn sáng', 'ăn khuya'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 3,
                'item_type'      => 'restaurant',
                'name'           => 'Cơm tấm Ba Ghiền',
                'description'    => 'Nức tiếng với miếng sườn nướng than hoa siêu to khổng lồ',
                'price_min'      => 80000,
                'price_max'      => 120000,
                'duration_hours' => 1.0,
                'open_time'      => '07:00',
                'close_time'     => '21:00',
                'rating'         => 4.5,
                'tags'           => ['đặc sản', 'ăn trưa', 'no bụng'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // 2 Hotels
            [
                'destination_id' => 3,
                'item_type'      => 'hotel',
                'name'           => 'Saigonciti Hotel',
                'description'    => 'Khách sạn nhỏ tiện lợi nằm gần khu phố Tây Bùi Viện',
                'price_min'      => 450000,
                'price_max'      => 550000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.0,
                'tags'           => ['tiết kiệm', 'sôi động', 'trung tâm'],
                'suitable_for'   => ['solo', 'couple'],
            ],
            [
                'destination_id' => 3,
                'item_type'      => 'hotel',
                'name'           => 'Liberty Central Saigon Centre',
                'description'    => 'Khách sạn chuẩn 4 sao hiện đại, tiện nghi ngay quận 1',
                'price_min'      => 1400000,
                'price_max'      => 1700000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.6,
                'tags'           => ['sang trọng', 'nghỉ dưỡng', 'thuận tiện'],
                'suitable_for'   => ['family', 'couple'],
            ],

            // 1 Activity
            [
                'destination_id' => 3,
                'item_type'      => 'activity',
                'name'           => 'Ăn tối trên du thuyền sông Sài Gòn',
                'description'    => 'Ngắm cảnh thành phố hoa lệ về đêm dọc theo bờ sông Sài Gòn',
                'price_min'      => 300000,
                'price_max'      => 500000,
                'duration_hours' => 2.5,
                'open_time'      => '18:00',
                'close_time'     => '21:30',
                'rating'         => 4.5,
                'tags'           => ['lãng mạn', 'buổi tối', 'ngắm cảnh'],
                'suitable_for'   => ['couple', 'family'],
            ],

            // ================= ĐÀ LẠT (destination_id = 4) =================

            // 3 Attractions
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Khu Du lịch Langbiang',
                'description'    => 'Đỉnh núi cao nhất Đà Lạt, trải nghiệm đi xe Jeep và ngắm toàn cảnh',
                'price_min'      => 50000,
                'price_max'      => 120000,
                'duration_hours' => 3.0,
                'open_time'      => '07:00',
                'close_time'     => '17:00',
                'rating'         => 4.4,
                'tags'           => ['thiên nhiên', 'ngoài trời', 'chụp ảnh'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Thung lũng Tình Yêu',
                'description'    => 'Khuôn viên ngập tràn hoa, hồ nước lãng mạn và các tiểu cảnh check-in',
                'price_min'      => 250000,
                'price_max'      => 250000,
                'duration_hours' => 3.0,
                'open_time'      => '07:00',
                'close_time'     => '17:00',
                'rating'         => 4.2,
                'tags'           => ['ngắm cảnh', 'lãng mạn', 'sống ảo'],
                'suitable_for'   => ['couple', 'family'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Vườn hoa Thành phố Đà Lạt',
                'description'    => 'Quy tụ hàng ngàn loài hoa tuyệt đẹp đua sắc quanh năm',
                'price_min'      => 100000,
                'price_max'      => 100000,
                'duration_hours' => 2.0,
                'open_time'      => '07:00',
                'close_time'     => '18:00',
                'rating'         => 4.3,
                'tags'           => ['hoa', 'nhẹ nhàng', 'chụp ảnh'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // 3 Restaurants
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Lẩu gà lá é Tao Ngộ',
                'description'    => 'Món lẩu trứ danh cực kỳ phù hợp với thời tiết se lạnh của Đà Lạt',
                'price_min'      => 200000,
                'price_max'      => 300000,
                'duration_hours' => 1.5,
                'open_time'      => '10:00',
                'close_time'     => '23:00',
                'rating'         => 4.6,
                'tags'           => ['đặc sản', 'ăn tối', 'ấm áp'],
                'suitable_for'   => ['family', 'couple'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Bánh căn Lệ',
                'description'    => 'Bánh căn nóng hổi nhân xíu mại, trứng cút trong hẻm nhỏ',
                'price_min'      => 30000,
                'price_max'      => 50000,
                'duration_hours' => 1.0,
                'open_time'      => '07:00',
                'close_time'     => '17:00',
                'rating'         => 4.5,
                'tags'           => ['ẩm thực đường phố', 'ăn sáng', 'đặc sản'],
                'suitable_for'   => ['solo', 'couple', 'family'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Lẩu bò Quán Gỗ (Ba Toa)',
                'description'    => 'Quán lẩu bò mộc mạc, miếng bò dày thịt, nước dùng đậm đà',
                'price_min'      => 250000,
                'price_max'      => 400000,
                'duration_hours' => 1.5,
                'open_time'      => '10:00',
                'close_time'     => '22:00',
                'rating'         => 4.4,
                'tags'           => ['đặc sản', 'nhà hàng', 'ăn trưa'],
                'suitable_for'   => ['family', 'couple'],
            ],

            // 2 Hotels
            [
                'destination_id' => 4,
                'item_type'      => 'hotel',
                'name'           => 'Tigold Hostel Da Lat',
                'description'    => 'Chỗ nghỉ homestay phong cách trẻ trung, tiết kiệm chi phí',
                'price_min'      => 300000,
                'price_max'      => 500000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.3,
                'tags'           => ['tiết kiệm', 'thân thiện', 'gần chợ'],
                'suitable_for'   => ['solo', 'couple'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'hotel',
                'name'           => 'Hôtel Colline Đà Lạt',
                'description'    => 'Khách sạn 4 sao đẳng cấp nằm ngay phía trên chợ Đà Lạt Mới',
                'price_min'      => 1400000,
                'price_max'      => 1900000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.7,
                'tags'           => ['sang trọng', 'hiện đại', 'trung tâm'],
                'suitable_for'   => ['family', 'couple'],
            ],

            // 1 Activity
            [
                'destination_id' => 4,
                'item_type'      => 'activity',
                'name'           => 'Trải nghiệm hái dâu tây tại vườn',
                'description'    => 'Tự tay hái dâu tây tươi sạch ngay tại nhà vườn sinh thái',
                'price_min'      => 100000,
                'price_max'      => 200000,
                'duration_hours' => 2.0,
                'open_time'      => '08:00',
                'close_time'     => '16:00',
                'rating'         => 4.5,
                'tags'           => ['nông nghiệp', 'trải nghiệm', 'gia đình'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // ================= PHÚ QUỐC (destination_id = 4) =================

            // 3 Attractions
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Vườn Quốc gia Phú Quốc',
                'description'    => 'Khu rừng nguyên sinh rộng hơn 31.400 ha, được UNESCO công nhận là khu dự trữ sinh quyển thế giới, lý tưởng cho trekking và quan sát động vật hoang dã',
                'price_min'      => 0,
                'price_max'      => 0,
                'duration_hours' => 3.0,
                'open_time'      => '07:00',
                'close_time'     => '17:00',
                'rating'         => 4.6,
                'tags'           => ['thiên nhiên', 'trekking', 'sinh thái'],
                'suitable_for'   => ['family', 'solo', 'couple'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Bãi Sao',
                'description'    => 'Bãi biển đẹp nhất Phú Quốc với cát trắng mịn và nước trong xanh, tọa lạc phía Nam đảo tại thị trấn An Thới, an toàn và êm đềm quanh năm',
                'price_min'      => 0,
                'price_max'      => 0,
                'duration_hours' => 3.0,
                'open_time'      => '06:00',
                'close_time'     => '18:00',
                'rating'         => 4.7,
                'tags'           => ['biển', 'tắm biển', 'chụp ảnh'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Dinh Cậu',
                'description'    => 'Ngôi đền tâm linh biểu tượng ngay trung tâm thị trấn Dương Đông, tọa lạc trên mỏm đá hướng ra biển, nổi tiếng là điểm ngắm hoàng hôn đẹp nhất đảo',
                'price_min'      => 0,
                'price_max'      => 0,
                'duration_hours' => 1.0,
                'open_time'      => '06:00',
                'close_time'     => '18:00',
                'rating'         => 4.5,
                'tags'           => ['tâm linh', 'hoàng hôn', 'ngắm cảnh'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // 3 Restaurants
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Nhà hàng Crab House Phú Quốc',
                'description'    => 'Địa chỉ hải sản nổi tiếng nhất đảo chuyên các món ghẹ tươi sống, nằm tại 108 đường 30 Tháng 4, Dương Đông',
                'price_min'      => 200000,
                'price_max'      => 500000,
                'duration_hours' => 1.5,
                'open_time'      => '10:00',
                'close_time'     => '22:00',
                'rating'         => 4.5,
                'tags'           => ['hải sản', 'ghẹ', 'ăn trưa'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Bún Kèn Út Lượm',
                'description'    => 'Quán bún kèn đặc sản Phú Quốc nổi tiếng nhất đảo, sợi bún gạo ăn kèm nước dùng cá đậm đà và rau thơm, địa chỉ đường 30/4 Dương Đông',
                'price_min'      => 40000,
                'price_max'      => 60000,
                'duration_hours' => 1.0,
                'open_time'      => '07:00',
                'close_time'     => '14:00',
                'rating'         => 4.6,
                'tags'           => ['đặc sản', 'ăn sáng', 'bình dân'],
                'suitable_for'   => ['solo', 'couple', 'family'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Nhà hàng Thiên Thanh',
                'description'    => 'Nhà hàng hải sản lâu năm nổi tiếng tại trung tâm Dương Đông, thực đơn phong phú từ tôm hùm đến ghẹ hấp, không gian rộng thoáng, địa chỉ đường 30 Tháng 4 Kp1',
                'price_min'      => 150000,
                'price_max'      => 400000,
                'duration_hours' => 1.5,
                'open_time'      => '10:00',
                'close_time'     => '22:00',
                'rating'         => 4.4,
                'tags'           => ['hải sản', 'nhà hàng', 'ăn tối'],
                'suitable_for'   => ['family', 'couple'],
            ],

            // 2 Hotels
            [
                'destination_id' => 4,
                'item_type'      => 'hotel',
                'name'           => 'Phú Quốc Budget Hostel',
                'description'    => 'Chỗ nghỉ bình dân giá tốt gần trung tâm thị trấn Dương Đông, phù hợp cho khách solo và cặp đôi tiết kiệm chi phí',
                'price_min'      => 200000,
                'price_max'      => 400000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.0,
                'tags'           => ['tiết kiệm', 'trung tâm', 'tiện lợi'],
                'suitable_for'   => ['solo', 'couple'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'hotel',
                'name'           => 'Salinda Resort Phu Quoc',
                'description'    => 'Resort boutique 5 sao sang trọng nằm trên bãi Trường với view hoàng hôn tuyệt đẹp và bể bơi vô cực nhìn ra biển',
                'price_min'      => 3000000,
                'price_max'      => 6000000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.8,
                'tags'           => ['sang trọng', 'nghỉ dưỡng', 'view biển'],
                'suitable_for'   => ['couple', 'family'],
            ],

            // 2 Activities
            [
                'destination_id' => 4,
                'item_type'      => 'activity',
                'name'           => 'Lặn ngắm san hô Hòn Thơm',
                'description'    => 'Tour lặn biển khám phá hơn 100 loài san hô và sinh vật biển tại đảo Hòn Thơm, kết hợp đi cáp treo vượt biển dài nhất thế giới',
                'price_min'      => 300000,
                'price_max'      => 600000,
                'duration_hours' => 4.0,
                'open_time'      => '08:00',
                'close_time'     => '16:00',
                'rating'         => 4.7,
                'tags'           => ['lặn biển', 'san hô', 'cáp treo'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'activity',
                'name'           => 'Chợ đêm Dương Đông',
                'description'    => 'Chợ đêm lớn nhất Phú Quốc ngay trung tâm thị trấn, hàng trăm gian hàng hải sản tươi sống, đặc sản địa phương và quà lưu niệm sôi động về đêm',
                'price_min'      => 50000,
                'price_max'      => 300000,
                'duration_hours' => 2.0,
                'open_time'      => '18:00',
                'close_time'     => '23:00',
                'rating'         => 4.4,
                'tags'           => ['ẩm thực', 'chợ đêm', 'mua sắm'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            // Thêm Attractions
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Bãi Dài Phú Quốc',
                'description'    => 'Bãi biển hoang sơ dài 15km tại phía Bắc đảo, nước trong xanh và sóng nhẹ, ít người biết nên rất yên tĩnh và thơ mộng',
                'price_min'      => 0,
                'price_max'      => 0,
                'duration_hours' => 3.0,
                'open_time'      => '06:00',
                'close_time'     => '18:00',
                'rating'         => 4.6,
                'tags'           => ['biển', 'hoang sơ', 'yên tĩnh'],
                'suitable_for'   => ['couple', 'solo'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Nhà thùng nước mắm Khải Hoàn',
                'description'    => 'Tham quan quy trình sản xuất nước mắm truyền thống Phú Quốc lâu đời nhất đảo, mua đặc sản mang về tại đường 30/4 Dương Đông',
                'price_min'      => 0,
                'price_max'      => 0,
                'duration_hours' => 1.0,
                'open_time'      => '07:00',
                'close_time'     => '17:00',
                'rating'         => 4.3,
                'tags'           => ['đặc sản', 'tham quan', 'mua sắm'],
                'suitable_for'   => ['family', 'solo', 'couple'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'attraction',
                'name'           => 'Làng chài Hàm Ninh',
                'description'    => 'Làng chài cổ hơn 200 năm tuổi phía Đông đảo, nổi tiếng với ghẹ Hàm Ninh hấp gừng và cảnh bình minh trên biển tuyệt đẹp',
                'price_min'      => 0,
                'price_max'      => 0,
                'duration_hours' => 2.0,
                'open_time'      => '06:00',
                'close_time'     => '18:00',
                'rating'         => 4.4,
                'tags'           => ['làng chài', 'bình minh', 'văn hóa'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // Thêm Restaurants
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Nhà hàng Hải Sản Gành Dầu',
                'description'    => 'Nhà hàng hải sản tươi sống tại mũi Gành Dầu cực Bắc đảo, chuyên tôm hùm và cá mú, view biển nhìn sang Campuchia',
                'price_min'      => 200000,
                'price_max'      => 500000,
                'duration_hours' => 1.5,
                'open_time'      => '10:00',
                'close_time'     => '21:00',
                'rating'         => 4.5,
                'tags'           => ['hải sản', 'view biển', 'ăn trưa'],
                'suitable_for'   => ['family', 'couple'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Nhà hàng Ốc Nhỏ Phú Quốc',
                'description'    => 'Quán ốc bình dân nổi tiếng tại đường Trần Hưng Đạo, Dương Đông, chuyên ốc hấp sả, nghêu xào me và hải sản giá rẻ',
                'price_min'      => 80000,
                'price_max'      => 200000,
                'duration_hours' => 1.5,
                'open_time'      => '16:00',
                'close_time'     => '23:00',
                'rating'         => 4.3,
                'tags'           => ['ốc', 'bình dân', 'ăn tối'],
                'suitable_for'   => ['solo', 'couple', 'family'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'restaurant',
                'name'           => 'Quán Ghẹ Hàm Ninh',
                'description'    => 'Đặc sản ghẹ Hàm Ninh hấp gừng nổi tiếng nhất Phú Quốc, ăn ngay tại làng chài với view biển, giá bình dân',
                'price_min'      => 150000,
                'price_max'      => 350000,
                'duration_hours' => 1.5,
                'open_time'      => '09:00',
                'close_time'     => '20:00',
                'rating'         => 4.6,
                'tags'           => ['ghẹ', 'đặc sản', 'làng chài'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],

            // Thêm Activities
            [
                'destination_id' => 4,
                'item_type'      => 'activity',
                'name'           => 'Cáp treo Hòn Thơm',
                'description'    => 'Đi cáp treo vượt biển dài nhất thế giới 7.899m từ An Thới ra đảo Hòn Thơm, ngắm toàn cảnh biển xanh và quần đảo An Thới từ trên cao',
                'price_min'      => 300000,
                'price_max'      => 400000,
                'duration_hours' => 2.0,
                'open_time'      => '08:00',
                'close_time'     => '17:00',
                'rating'         => 4.8,
                'tags'           => ['cáp treo', 'ngắm cảnh', 'check-in'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'activity',
                'name'           => 'Tour câu cá và lặn ngắm san hô',
                'description'    => 'Tour 4 đảo kết hợp câu cá, lặn ngắm san hô và tắm biển quanh quần đảo An Thới, xuất phát từ cảng An Thới buổi sáng sớm',
                'price_min'      => 250000,
                'price_max'      => 450000,
                'duration_hours' => 5.0,
                'open_time'      => '07:00',
                'close_time'     => '14:00',
                'rating'         => 4.7,
                'tags'           => ['tour biển', 'câu cá', 'lặn biển'],
                'suitable_for'   => ['family', 'couple', 'solo'],
            ],
            [
                'destination_id' => 4,
                'item_type'      => 'activity',
                'name'           => 'VinWonders Phú Quốc',
                'description'    => 'Công viên giải trí và vui chơi lớn nhất Phú Quốc với hơn 100 trò chơi, show diễn và khu nước, nằm trong quần thể Vinpearl tại bãi Dài',
                'price_min'      => 600000,
                'price_max'      => 900000,
                'duration_hours' => 6.0,
                'open_time'      => '09:00',
                'close_time'     => '21:00',
                'rating'         => 4.5,
                'tags'           => ['vui chơi', 'gia đình', 'giải trí'],
                'suitable_for'   => ['family', 'couple'],
            ],
            
            // Thêm Hotel
            [
                'destination_id' => 4,
                'item_type'      => 'hotel',
                'name'           => 'Vinpearl Resort & Spa Phú Quốc',
                'description'    => 'Resort 5 sao đẳng cấp tại bãi Dài với bãi biển riêng dài 1km, hồ bơi vô cực và kết nối trực tiếp với VinWonders',
                'price_min'      => 2500000,
                'price_max'      => 5000000,
                'duration_hours' => 24.0,
                'open_time'      => null,
                'close_time'     => null,
                'rating'         => 4.7,
                'tags'           => ['5 sao', 'bãi biển riêng', 'nghỉ dưỡng'],
                'suitable_for'   => ['family', 'couple'],
            ],
        ];

        

        foreach ($attractions as $a) {
            // 1. Tự động đổi chữ 'destination_id' thành 'location_id' cho đúng với DB
            if (isset($a['destination_id'])) {
                $a['location_id'] = $a['destination_id'];
                unset($a['destination_id']);
            }
            
            // 2. Vứt bỏ các cột DB chưa có để tránh lỗi SQL
            unset($a['rating'], $a['tags'], $a['suitable_for']);

            // 3. Insert vào DB
            Attraction::create($a);
        }

        // TODO: Tương tự cho Hà Nội, HCM, Phú Quốc, Đà Lạt
    }
}